---
title: "Visualizaciones sobre el conjunto de datos Iris"
format: dashboard
---

```{r}
#| label: carga-paquetes

library(tidyverse)
library(plotly)
```


## Row

```{r}
#| label: grafico-ancho-vs-largo-petalo
#| title: "Relación entre el ancho y largo de los pétalos"

grafico_ggplot2 <-
iris |>
  ggplot(aes(
    x = Petal.Width,
    y = Petal.Length
  )) +
  geom_point() +
  geom_smooth(method = "lm")

ggplotly(grafico_ggplot2) |> config(locale = "es")
```

```{r}
#| label: grafico-ancho-vs-largo-sepalo
#| title: "Relación entre el ancho y el largo de los sépalos"

grafico_ggplot2 <-
iris |>
  ggplot(aes(
    x = Sepal.Width,
    y = Sepal.Length
  )) +
  geom_point() +
  geom_smooth(method = "lm")

ggplotly(grafico_ggplot2) |> config(locale = "es")
```

## Row {.tabset}

```{r}
#| label: grafico-promedio-longitud-petalo-x-especie
#| title: Promedio de longitud de pétalos por especie

grafico_ggplot2 <-
iris |>
  group_by(Species) |>
  summarize(promedio_lontitud_petalo = mean(Petal.Length, na.rm = TRUE)) |>
  ggplot(aes(
    x = Species,
    y = promedio_lontitud_petalo
  )) +
  geom_col()

ggplotly(grafico_ggplot2) |> config(locale = "es")
```

```{r}
#| label: grafico-promedio-longitud-sepalo-x-especie
#| title: Promedio de longitud de sépalos por especie

grafico_ggplot2 <-
iris |>
  group_by(Species) |>
  summarize(promedio_lontitud_sepalo = mean(Sepal.Length, na.rm = TRUE)) |>
  ggplot(aes(
    x = Species,
    y = promedio_lontitud_sepalo
  )) +
  geom_col()

ggplotly(grafico_ggplot2) |> config(locale = "es")
```